<a href="https://colab.research.google.com/github/QuanPhan78/thuchanhdeeplearning/blob/main/thuchanhlab1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành bài Lab 1

In [ ]:
import numpy as np

list = [1, 2, 2, 3]
print(list)
numpy_list = np.array(list)
print(numpy_list)

[1, 2, 2, 3]
[1 2 2 3]


In [ ]:
import numpy as np


c = np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
import numpy as np

c = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(c)
print(c.shape)
print(c.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
int64


In [ ]:
import numpy as np

e = np.zeros((2,2))
f = np.ones((3,3))
print(e)
print()
print(f)

[[0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

e = np.array([[1,2,3],[4,5,6]])
print(e)
print(e.shape)
print()
f = e.reshape(3,2)
print(f)
print(f.shape)
print()
g = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(g)
print(g.shape)
print(g.reshape(3,4))
j = g.reshape(3,4).reshape(3,2,2)
print("\n\n",j)
print("\n\n",j.flatten())

print("\n\n")
a = np.random.randint(100, size =(5,2))
print(a)
print("\n\n")
b = np.random.randint(-100,200, size =(3,4,4))
print(b)


[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


 [ 1  2  3  4  5  6  7  8  9 10 11 12]



[[79 23]
 [ 4 29]
 [25 38]
 [11 48]
 [92 73]]



[[[-37 -27  97 149]
  [ 22  87  52 187]
  [-30  13 -58 -59]
  [ 96  93  49 -73]]

 [[ -6 -14 116  -5]
  [ 60 -60 153 180]
  [ 42 -67  38  55]
  [-10 -41 -66 151]]

 [[ 71 -90 -76 117]
  [ 25 -29 112 -57]
  [136 177 154  96]
  [ 12  -8 154 -27]]]


In [ ]:
#Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
import numpy as np

a = np.random.normal(10, 1, 4)
print(a)

#Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước
b = np.random.choice(["a","b","c"])
print(b)

c = np.random.choice(["a","b","c"], size =(2,2))
print(c)

#Thay đổi giá trị của ma trận

A = np.matrix(np.zeros((4,4)))
print(A)
np.array(A)[2]=2 #array
print(A)
np.asarray(A)[1]=2 #asarray
print(A)


[10.0569586   9.22944578 10.88387459 11.14287077]
b
[['c' 'a']
 ['a' 'b']]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [2. 2. 2. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
#Dùng hàm arange
a = np.arange(1,20)
print(a)
#Dùng hàm arange với bước nhảy
b = np.arange(1,20,2)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


# Thực hành Lab 2


In [ ]:
import tensorflow as tf

print("--- 3.1. Tensor 0-chiều ---")
# Tạo một tensor scalar có giá trị là 4
rank_0_tensor = tf.constant(4)
print("rank_0_tensor:", rank_0_tensor)

# Tạo tensor scalar với kiểu dữ liệu int16, float32 và string
r1 = tf.constant(9, tf.int16)
print("r1:", r1)

r1_float = tf.constant(1.12, tf.float32)
print("r1_float:", r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print("r1_string:", r1_string)
print("\n")


print("--- 3.2. Tensor 1-chiều ---")
# Tạo tensor 1-chiều gồm 3 phần tử
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print("rank_1_tensor:\n", rank_1_tensor)
print("\n")


print("--- 3.3. Tensor 2-chiều (ma trận) ---")
# Tạo tensor 2-chiều (ma trận)
rank_2_tensor = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=tf.float16)
print("rank_2_tensor:\n", rank_2_tensor)
print("\n")


print("--- 3.4. Tensor n-chiều (nhiều trục) ---")
# Tạo tensor 3-chiều
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]
])
print("rank_3_tensor:\n", rank_3_tensor)
print("\n")


print("--- 3.5. Thuộc tính của tensor ---")
# Kiểm tra thuộc tính của tensor 3-chiều (rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)
print()

print("--- 3.6. Tạo tensor tự động gán giá trị 0 ban đầu ---")
# Tạo tensor 1-chiều với 10 phần tử có giá trị 0
t_zero = tf.zeros(10)
print("t_zero:\n", t_zero)
print("\n")

# Tạo tensor 2-chiều (ma trận 3x3) với các phần tử có giá trị 0
t_2_zero = tf.zeros([3, 3])
print("t_2_zero:\n", t_2_zero)
print("\n")

# Tạo tensor 3-chiều (kích thước 3x3x5) với các phần tử có giá trị 0
t_3_zero = tf.zeros([3, 3, 5])
print("t_3_zero:\n", t_3_zero)

--- 3.1. Tensor 0-chiều ---
rank_0_tensor: tf.Tensor(4, shape=(), dtype=int32)
r1: tf.Tensor(9, shape=(), dtype=int16)
r1_float: tf.Tensor(1.12, shape=(), dtype=float32)
r1_string: tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


--- 3.2. Tensor 1-chiều ---
rank_1_tensor:
 tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


--- 3.3. Tensor 2-chiều (ma trận) ---
rank_2_tensor:
 tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


--- 3.4. Tensor n-chiều (nhiều trục) ---
rank_3_tensor:
 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


--- 3.5. Thuộc tính của tensor ---
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>

--- 3.6. Tạo tensor tự động gán giá trị 0 ban đầu ---
t_zero:
 tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


t_2_zero:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


