<a href="https://colab.research.google.com/github/QuanPhan78/thuchanhdeeplearning/blob/main/ThucHanhBuoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# THỰC HÀNH 1 : NUMPY & PANDAS
## 1. GIỚI THIỆU NUMPY
* Numpy là thư viện dành cho lập trình toán học, khoa học, kỹ thuật và khoa học dữ liệu.
* Numpy xử lý rất tốt các đối tượng mảng đa chiều và ma trận, đặc biệt là khối lượng dữ liệu lớn với tốc độ rất nhanh.
* Tensorflow và Scikit sử dụng Numpy để tính toán ma trận ở backend.


## 2. CÀI ĐẶT NUMPY

In [1]:
import numpy as np

## 3. TẠO NUMPY ARRAY
### 3.1. Tạo array 1-chiều
* Có thể dùng thuộc tính `shape`, `dtype` để xem kích thước mảng và kiểu dữ liệu.

In [2]:
# Cách 1: tạo list rồi chuyển thành Numpy array
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2: Khởi tạo trực tiếp
a = np.array([1, 9, 15, 39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


### 3.2. Array 2-chiều
### 3.3. Array 3-chiều

In [3]:
# Array 2-chiều
c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print("Shape:", c.shape)
print("Dtype:", c.dtype)

# Array 3-chiều
d = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(d)
print("Shape:", d.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Shape: (2, 2, 3)


### 3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [4]:
e = np.zeros((2, 2)) # Ma trận toàn số 0
f = np.ones((3, 3))  # Ma trận toàn số 1
print('Zero matrix: \n', e)
print('One matrix\n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3.5. Reshape và Flatten ma trận
* **3.5.1. Reshape:** Thay đổi kích thước ma trận.
* **3.5.2. Flatten:** Chuyển array nhiều chiều về 1 chiều.

In [5]:
# Reshape
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print('Shape ban đầu:', g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

# Flatten
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f_flat = e.flatten()
print("Flatten ma trận e:", f_flat)

j_flat = g.flatten()
print("Flatten ma trận g:", j_flat)

Shape ban đầu: (2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
Flatten ma trận e: [1. 2. 3. 4. 5. 6.]
Flatten ma trận g: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


### 3.6. Thêm dòng dữ liệu với hstack và vstack
* Hàm `hstack((x, y))` cho phép thêm nối thêm dữ liệu ma trận y vào sau ma trận x (chiều ngang).
* Hàm `vstack((x, y))` cho phép thêm nối thêm dữ liệu ma trận y vào dưới ma trận x (chiều dọc).

In [7]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


### 3.7. Sinh mảng số ngẫu nhiên
* **3.7.1.** Sinh mảng số nguyên ngẫu nhiên.
* **3.7.2.** Sinh mảng số thực trong khoảng [0, 1].
* **3.7.3.** Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian: Dùng hàm `Numpy.random.normal(loc, scale, size)` với `loc` là giá trị trung tâm, `scale` là độ lệch chuẩn, `size` là số phần tử.
* **3.7.4.** Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước.

In [10]:
# 3.7.1. Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

# 3.7.2. Sinh mảng số thực trong khoảng [0, 1]
a_rand = np.random.rand(5)
print('Random 1-D array [0,1]\n', a_rand)

# 3.7.3. Phân phối chuẩn Gaussian
a_norm = np.random.normal(5, 0.5, 10)
print('Phân phối chuẩn: \n', a_norm)

# 3.7.4. Lấy ngẫu nhiên từ mảng cho trước
a_choice = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print('1 giá trị ngẫu nhiên:', a_choice)

b_choice = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print('Ma trận ngẫu nhiên từ mảng: \n', b_choice)

Random 1-D array
 [ 5 19 57 68 83]
Random 2-D array
 [[ 0 75  0 65]
 [49  9 64 98]
 [75 16 40  9]]
Random 3-D array
 [[[82  1 27]
  [50  5 30]
  [60 65 84]
  [63 57 49]]

 [[98 99 67]
  [88 11 73]
  [71 40 66]
  [14 81 13]]

 [[51 64 85]
  [92 80 51]
  [26 16 92]
  [34 37 52]]]
Random 1-D array [0,1]
 [0.59365613 0.79494193 0.22976558 0.82337635 0.11842825]
Phân phối chuẩn: 
 [4.83611669 4.91203107 4.62336978 5.70000076 5.01170802 4.46090726
 5.33360941 4.51558426 4.55948464 5.79749437]
1 giá trị ngẫu nhiên: 8
Ma trận ngẫu nhiên từ mảng: 
 [[ 4 20  8 12 16]
 [20  2  8 12  2]
 [ 4 18 18  4 12]]


### 3.8. Thay đổi giá trị của ma trận
* Các giá trị trong ma trận là bất biến. Cần chuyển đối tượng thành numpy array hoặc asarray để thay đổi.

### 3.9. Sinh dãy số theo khoảng cho trước
* Dùng hàm `arange` hoặc `linspace`.

### 3.10. Index và slice
* Giá trị trước dấu `,` là số dòng, sau dấu `,` là số cột. Thêm `:` để chọn toàn bộ dòng/cột cụ thể.

In [12]:
# 3.8. Thay đổi giá trị ma trận
A = np.matrix(np.ones((5, 5)))
np.array(A)[2] = 2
print('Change values of third row with array\n', A)

# 3.9. Sinh dãy số
a_arange = np.arange(1, 20)
b_arange = np.arange(1, 20, 2) # Tăng 2 giá trị mỗi bước
print(b_arange)

a_lin = np.linspace(1., 5., num=10)
print(a_lin)

# 3.10. Index và slice
a_idx = np.array([(1, 2, 3), (4, 5, 6)])
print('second row:', a_idx[1])
print('Second column:', a_idx[:, 1])
print('First two values of second row:', a_idx[1, :2])

Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 1  3  5  7  9 11 13 15 17 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
second row: [4 5 6]
Second column: [2 5]
First two values of second row: [4 5]


## 4. GIỚI THIỆU PANDAS
* Là thư viện mở của Python chuyên xử lý dữ liệu dạng bảng và chuỗi thời gian.
* Pandas dựa trên tầng cơ sở Numpy, xử lý missing data dễ dàng.
* Dùng đối tượng `Series` xử lý data 1-chiều và `DataFrame` để xử lý data 2-chiều.

## 5. CÀI ĐẶT PANDAS

In [13]:
import pandas as pd

## 6. TÌM HIỂU ĐỐI TƯỢNG SERIES
* Series là cấu trúc dữ liệu 1-chiều.

In [14]:
# Tạo pandas series từ list
a_series = pd.Series([1., 2., 3.])
print(a_series)
print('First value:', a_series[0])

b_series = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b_series)

# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
day1    420
day2    380
day3    390
dtype: int64


## 7. TẠO ĐỐI TƯỢNG DATAFRAME
* DataFrame là mảng 2-chiều có nhãn ở 2 trục.
* Có thể chuyển đổi qua lại giữa Numpy và Pandas dễ dàng.

In [15]:
# Numpy <--> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

# Tạo DataFrame có tên cột từ dictionary
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

# Tạo mảng 20x4 và slice DataFrame
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # in 5 dòng đầu tiên

print('Chọn cột so1\n', df['so1'])
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, 2])

# Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df.head(2))

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]
    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  2.093945  0.784755 -0.243241 -0.092642
1 -1.097919  0.921254  0.380268  1.359723
2 -1.024598 -0.885088 -1.322003 -0.631005
3  0.981364  1.314319  1.432012  0.065495
4  0.573128 -0.145357 -0.956263 -0.219912
Chọn cột so1
 0     2.093945
1    -1.097919
2    -1.024598
3     0.981364
4     0.573128
5    -1.802180
6    -0.454081
7     0.116357
8     0.498151
9    -0.901525
10    0.639308
11   -0.646390
12   -0.403236
13    0.080695
14    0.241070
15   -0.317480
16   -0.757832
17   -1.327257
18    0.196194
19    0.219093
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  2.093945  0.784755 -0.243241 -0.092642
1 -1.097919  0.921254  0.380268  1.359723
2 -1.024598 -0.885088 -1.322003 -0.631005
Chọn nhiều cột
          so1       so3
0   2.093945 -0.243241
1  -1.097919  0.380268
2  -1.024598 -1.322003
3   0.

### 7.1. Nối nhiều DataFrame

In [16]:
# Nối 2 DataFrame
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [26, 11]}, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị trùng lặp
print('Drop duplicate values\n', df_concat.drop_duplicates('Name'))

# Sắp xếp theo cột
print('Sort values\n', df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


# THỰC HÀNH 2: CƠ BẢN TENSORFLOW
##  GIỚI THIỆU TENSORFLOW
* Tensor là một vector hay ma trận n-chiều biểu diễn cho tất cả các kiểu dữ liệu.
* Tất cả giá trị trong một tensor có cùng kiểu dữ liệu còn gọi là shape.
* Shape của dữ liệu là chiều của ma trận hoặc mảng (array).
* Tensorflow là 1 framework xử lý các tensor.
* Tất cả các tính toán đều được thực hiện trên graph.
* Graph là tập các phép toán được thực hiện liên tục.
* Mỗi phép toán được gọi là 1 opnode và có liên kết với nhau.



## 2. MÔI TRƯỜNG LẬP TRÌNH
Chèn thư viện tensorflow và numpy

In [18]:
import tensorflow as tf
import numpy as np

## 3. BIỂU DIỄN MỘT TENSOR
### 3.1. Tensor 0-chiều
* Tensor 0-chiều gọi là scalar chỉ chứa 1 giá trị và không có trục.

In [19]:
# Tạo một tensor scalar có giá trị là 4 (Mặc định tạo một tensor có kiểu int32)
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Tạo một tensor scalar với kiểu dữ liệu là int16, float32 và string
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


### 3.2. Tensor 1-chiều
* Tensor 1-chiều còn gọi là vector có 1 trục.
* Tensor 1-chiều giống như một danh sách.

In [20]:
# Tạo tensor 1-chiều gồm 3 phần tử
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### 3.3. Tensor 2-chiều (ma trận)
* Là một ma trận hoặc có 2 trục.

In [21]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


### 3.4. Tensor n-chiều (nhiều trục)
* Ví dụ: tạo tensor 3-chiều.

In [22]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


### 3.5. Thuộc tính của tensor
Một tensor gồm có 3 thuộc tính:
* Label (name)
* Dimension (shape)
* Data type (dtype)

In [23]:
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


### 3.6. Tạo tensor tự động gán giá trị 0 ban đầu

In [24]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


### 3.7. Tạo tensor tự động gán giá trị 1 ban đầu

In [25]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


### 3.8. Tạo tensor tự động với giá trị bất kỳ
* Tạo tensor 1-chiều có 3 phần tử có giá trị 10.

In [26]:
t_1 = tf.fill([3], 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


### 3.9. Tạo tensor 1-chiều với hàm linspace
* Hàm linspace tạo một tensor với số phần tử mong muốn trong một phạm vi nhất định.

In [27]:
# Tạo 5 phần tử có giá trị trong khoảng [5.0, 20.0]
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


### 3.10. Tạo tensor 1-chiều với hàm range
* Hàm range tạo một tensor với số phần tử không được khai báo.
* Số phần tử sẽ được hàm tính bằng cách cộng thêm giá trị delta.

In [28]:
# Tạo một tensor trong khoảng [3.0, 7.0), mỗi giá trị mới cộng thêm delta = 0.5
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

# Tạo 1 tensor trong khoảng [0.0, 3.0), không khai báo giá trị ban đầu thì mặc định bắt đầu là 0.0
range_tensor2 = tf.range(3.0, delta=0.5)
print(range_tensor2)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


## 3.11. Tạo tensor với giá trị ngẫu nhiên
Tensorflow hỗ trợ nhiều hàm sinh số ngẫu nhiên:
* **`tf.random.normal`**: Tạo tensor với các giá trị theo phân phối chuẩn.
* **`tf.random.truncated_normal`**: Tạo tensor phân phối chuẩn nhưng loại bỏ các giá trị nằm ngoài 2 độ lệch chuẩn.
* **`tf.random.uniform`**: Tạo tensor với các giá trị phân phối đều giữa `minval` và `maxval`.
* **`tf.random.shuffle`**: Xáo trộn một tensor dọc theo chiều (dimension) đầu tiên của nó.

In [29]:
# random.normal
print("--- Normal ---")
norm_tensor_1 = tf.random.normal([5])
print(norm_tensor_1)
norm_tensor_2 = tf.random.normal([3, 3])
print(norm_tensor_2)

# random.truncated_normal
print("\n--- Truncated Normal ---")
trunc_tensor_1 = tf.random.truncated_normal([5])
print(trunc_tensor_1)
trunc_tensor_2 = tf.random.truncated_normal([3, 2, 2])
print(trunc_tensor_2)

# random.uniform
print("\n--- Uniform ---")
uni_tensor_1 = tf.random.uniform([5], minval=10, maxval=20)
print(uni_tensor_1)
uni_tensor_2 = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(uni_tensor_2)

# random.shuffle
print("\n--- Shuffle ---")
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print("Before shuffle:\n", range_tensor)
print("After shuffle:\n", tf.random.shuffle(range_tensor))

--- Normal ---
tf.Tensor([ 1.6564811   0.6890764   1.0393336   0.78284687 -0.26628116], shape=(5,), dtype=float32)
tf.Tensor(
[[-1.4342195  -0.752674    0.56217736]
 [-0.7393903   0.11843911  1.2797565 ]
 [-1.2645565   0.5825463   0.07165156]], shape=(3, 3), dtype=float32)

--- Truncated Normal ---
tf.Tensor([-0.5421304   1.0560795   0.30105868 -0.31911263  0.8007629 ], shape=(5,), dtype=float32)
tf.Tensor(
[[[-0.7452555  -0.24578492]
  [ 0.07895632 -1.0963165 ]]

 [[ 0.13038741 -0.12250683]
  [-0.32049718 -0.62520635]]

 [[-0.5084557   0.39061937]
  [-0.1941272   0.582317  ]]], shape=(3, 2, 2), dtype=float32)

--- Uniform ---
tf.Tensor([13.8052225 12.218473  13.228018  19.54906   19.279045 ], shape=(5,), dtype=float32)
tf.Tensor(
[[[15.9744215 18.744425  13.963514  17.065678  19.062614 ]
  [10.464106  17.014326  11.074657  17.112793  19.439257 ]]

 [[16.07825   18.060665  10.662351  17.556892  16.465733 ]
  [15.003815  16.247757  15.191006  15.654012  15.5588455]]

 [[17.660566  11.68

## 3.12. Chuyển đổi kiểu dữ liệu
* Để chuyển từ kiểu dữ liệu này sang kiểu khác ta dùng hàm `tf.cast`.

In [31]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, ', dtype:', t_float.dtype)

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, ', dtype:', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) , dtype: <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) , dtype: <dtype: 'int32'>


## 3.13. Các phép toán trong tensorflow
Cung cấp các phép toán cơ bản trên tensor:
* **`tf.sqrt`**: Tính căn bậc 2.
* **`tf.add` (hoặc `+`)**: Cộng 2 tensor.
* **`tf.multiply` (hoặc `*`)**: Nhân 2 tensor.
* Ngoài ra còn có: `tf.subtract` (trừ), `tf.divide` (chia), `tf.add_n` (cộng nhiều tensor), `tf.scalar_mul` (nhân với vô hướng), `tf.math.reciprocal` (nghịch đảo), `tf.negative` (phủ định).

In [32]:
# 3.13.1. Tính căn bậc 2
x = tf.constant(2, dtype=tf.float32)
print("Căn bậc 2:\n", tf.sqrt(x))

# 3.13.2. Cộng 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a, b)
d = a + b
print("\nCộng tensor (tf.add):\n", c)
print("Cộng tensor (toán tử +):\n", d)

# 3.13.3. Nhân 2 tensor
c_mul = tf.multiply(a, b)
d_mul = a * b
print("\nNhân tensor (tf.multiply):\n", c_mul)

# Thực hành các phép toán khác
a_f = tf.constant([6., 6., 6.])
b_f = tf.constant([4., 4., 4.])
c_f = tf.constant([3., 3., 3.])

print("\nCộng nhiều tensor (add_n):\n", tf.add_n([a_f, b_f, c_f]))
print("Trừ (subtract):\n", tf.subtract(a_f, b_f))
print("Nhân với vô hướng (scalar_mul):\n", tf.scalar_mul(3, a_f))
print("Phủ định (negative):\n", tf.negative(a_f))

Căn bậc 2:
 tf.Tensor(1.4142135, shape=(), dtype=float32)

Cộng tensor (tf.add):
 tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
Cộng tensor (toán tử +):
 tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)

Nhân tensor (tf.multiply):
 tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)

Cộng nhiều tensor (add_n):
 tf.Tensor([13. 13. 13.], shape=(3,), dtype=float32)
Trừ (subtract):
 tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
Nhân với vô hướng (scalar_mul):
 tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
Phủ định (negative):
 tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


## 3.14. Các phép toán làm tròn và so sánh
Các hàm thông dụng:
* **`tf.round`**: Làm tròn đến số nguyên gần nhất.
* **`tf.math.rint`**: Làm tròn đến số nguyên gần nhất (ưu tiên số chẵn nếu nằm ở giữa).
* **`tf.math.ceil`**: Làm tròn lên số nguyên gần nhất lớn hơn.
* **`tf.math.floor`**: Làm tròn xuống số nguyên gần nhất nhỏ hơn.
* **`tf.maximum` / `tf.minimum`**: Tìm giá trị lớn nhất / nhỏ nhất.
* **`tf.argmax` / `tf.argmin`**: Trả về index của phần tử lớn nhất / nhỏ nhất.

In [33]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print("Tensor gốc:", t.numpy())
print("Round:", r1.numpy())
print("Rint:", r2.numpy())
print("Ceil:", r3.numpy())
print("Floor:", r4.numpy())

Tensor gốc: [-6.5 -3.5  3.5  6.5]
Round: [-6. -4.  4.  6.]
Rint: [-6. -4.  4.  6.]
Ceil: [-6. -3.  4.  7.]
Floor: [-7. -4.  3.  6.]


## 3.15. Các phép toán trên vector và ma trận
* **`tensordot(a, b, axes, name=None)`:** Tính tổng các tích cho các phần tử trong trục được cung cấp.
* **`cross(a, b, name=None)`:** Trả về tích có hướng (cross product) của các phần tử.
* **`diag(diagonal, name=None)`:** Trả về ma trận đường chéo dựa trên các giá trị cung cấp, các phần tử còn lại bằng 0.
* **`trace(x, name=None)`:** Trả về tổng các phần tử trên đường chéo.
* **`transpose(x, perm=None, name='transpose')`:** Chuyển vị ma trận (đổi dòng thành cột).
* **`eye(num_rows, num_columns=None, batch_shape=None, dtype=tf.float32, name=None)`:** Tạo ma trận đơn vị.
* **`matmul(a, b, ...)`:** Nhân hai ma trận.
* **`norm(tensor, ...)`:** Trả về chuẩn (norm) của tensor.
* **`matrix_solve(A, b, ...)`:** Trả về tensor X thỏa mãn $AX = b$.

In [34]:
# Khởi tạo các tensor
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3], [4, 5, 6]])
t4 = tf.constant([[7, 8], [9, 10], [11, 12]])

# Thực hiện các phép toán
dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

# In kết quả
print("Tensordot (0):\n", dot_x)
print("Diag:\n", d)
print("Cross:\n", cross)
print("Trace:\n", trace)
print("Transpose:\n", trans)
print("Eye:\n", eye)

Tensordot (0):
 tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
Diag:
 tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
Cross:
 tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
Trace:
 tf.Tensor(6, shape=(), dtype=int32)
Transpose:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Eye:
 tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


## 3.16. Biến trong tensorflow
* Để khai báo một biến, ta sử dụng `tf.Variable`.
* Có thể sử dụng các hàm như `.assign()`, `.assign_add()`, `.assign_sub()` để thay đổi giá trị của biến.

In [35]:
# Khai báo biến
toan = tf.Variable(8.5, dtype=tf.float32)
print("Biến 'toan':\n", toan)

diem = tf.Variable([5, 9])
print("Biến 'diem':\n", diem)
print('Shape:', diem.shape)
print('Dtype:', diem.dtype)
print('numpy:', diem.numpy())

# Gán giá trị cho biến
diem.assign([8, 10])
print("\nSau khi gán [8, 10]:\n", diem)

diem.assign_add([1, 1])
print("\nSau khi cộng thêm [1, 1]:\n", diem)

diem.assign_sub([5, 5])
print("\nSau khi trừ đi [5, 5]:\n", diem)

Biến 'toan':
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
Biến 'diem':
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape: (2,)
Dtype: <dtype: 'int32'>
numpy: [5 9]

Sau khi gán [8, 10]:
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>

Sau khi cộng thêm [1, 1]:
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>

Sau khi trừ đi [5, 5]:
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


## 3.17. Môi trường tính toán Graph trong tensorflow
* Graph cho phép thực thi tính toán linh hoạt ngoài môi trường Python.
* Graph execution giúp Tensorflow chạy nhanh, tính toán song song và trên nhiều thiết bị (như thiết bị mobile, thiết bị nhúng).
* Graph là cấu trúc dữ liệu chứa các đối tượng `tf.Operation` (đơn vị tính toán) và `tf.Tensor` (đơn vị dữ liệu truyền qua lại).

### 3.17.1. Biến một hàm Python thuần túy sang graph
* Có thể dùng decorator `@tf.function` hoặc hàm `tf.function()` để biến một hàm Python thành graph.

In [38]:
# Cách 1: Sử dụng hàm tf.function
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

a_function_that_uses_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print("Original Function Value:", orig_value)
print("Tensorflow Graph Value:", tf_function_value)

# Cách 2: Sử dụng Decorator
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)
  return inner_function(x, y, b)

rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print("\nResult using Decorator:\n", rs)

Original Function Value: [[12.]]
Tensorflow Graph Value: [[12.]]

Result using Decorator:
 [[12.]]


## 3.18. Modules, Layers và Models
* **Model** là một hàm tính toán trên tensors, chứa một vài biến được cập nhật trong quá trình huấn luyện.
* Các model thường được cấu tạo từ các **layers** (các hàm cấu trúc toán học có thể tái sử dụng, có biến huấn luyện) được cài đặt dựa trên lớp cơ sở `tf.Module`.

In [37]:
# Tạo lớp SimpleModule xử lý tensor scalar (Layer)
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

  def __call__(self, x):
    return self.a_variable * x

simple_module = SimpleModule(name="simple")
rs = simple_module(tf.constant(5.0))

print("Kết quả tính toán:", rs)
print("Train variables:", simple_module.trainable_variables)
print("All variables:", simple_module.variables)

# Tạo model với nhiều tầng (layer)
class Dense(tf.Module):
  def __init__(self, in_features, out_features, name=None):
    super().__init__(name=name)
    self.w = tf.Variable(tf.random.normal([in_features, out_features]), name='w')
    self.b = tf.Variable(tf.zeros([out_features]), name='b')

  def __call__(self, x):
    y = tf.matmul(x, self.w) + self.b
    return tf.nn.relu(y)

class SequentialModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.dense_1 = Dense(in_features=3, out_features=3)
    self.dense_2 = Dense(in_features=3, out_features=2)

  def __call__(self, x):
    x = self.dense_1(x)
    return self.dense_2(x)

my_model = SequentialModule(name="the_model")
print("\nModel results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Kết quả tính toán: tf.Tensor(25.0, shape=(), dtype=float32)
Train variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)

Model results: tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


## 3.19. Lưu weight
* Có thể lưu `tf.Module` ở dạng checkpoint hoặc SavedModel.
* **Checkpoint** lưu trữ các weight (giá trị của tập biến trong model). Việc lưu tạo ra 2 file: `.data` (chứa giá trị biến) và `.index` (chứa số checkpoint).
* Sử dụng hàm `restore()` để khôi phục lại model.

In [39]:
# 3.19.1. Lưu checkpoint
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

# 3.19.2. Phục hồi checkpoint
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

print("Kết quả từ model đã khôi phục:", new_model(tf.constant([[2.0, 2.0, 2.0]])))

Kết quả từ model đã khôi phục: tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
