<a href="https://colab.research.google.com/github/QuanPhan78/thuchanhdeeplearning/blob/main/ThucHanhLab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

list = [1, 2, 2, 3]
print(list)
numpy_list = np.array(list)
print(numpy_list)

[1, 2, 2, 3]
[1 2 2 3]


In [4]:
import numpy as np


c = np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [10]:
import numpy as np

c = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(c)
print(c.shape)
print(c.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
int64


In [13]:
import numpy as np

e = np.zeros((2,2))
f = np.ones((3,3))
print(e)
print()
print(f)

[[0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
import numpy as np

e = np.array([[1,2,3],[4,5,6]])
print(e)
print(e.shape)
print()
f = e.reshape(3,2)
print(f)
print(f.shape)
print()
g = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(g)
print(g.shape)
print(g.reshape(3,4))
j = g.reshape(3,4).reshape(3,2,2)
print("\n\n",j)
print("\n\n",j.flatten())

print("\n\n")
a = np.random.randint(100, size =(5,2))
print(a)


[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


 [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[95 26]
 [28 16]
 [48  9]
 [10 26]
 [90  2]]
